version: "3.8"

services:
  base:
    build: .
    image: lechance/alpine:me
    container_name: base
    restart: unless-stopped
    hostname: alpine
    privileged: true
    stdin_open: true
    tty: true
    read_only: false
    environment:
      myName: "lechance"
    networks:
      - net
  base2:
    #build: .
    image: lechance/alpine:me
    container_name: base2
    restart: unless-stopped
    hostname: alpine2
    privileged: true
    stdin_open: true
    tty: true
    read_only: false
    environment:
      myName: "lechance"
    networks:
      - net

networks:
  net:
    external: true
