version: "3.8"

services:
  base:
    image: lechance/alpine:me
    container_name: base
    restart: unless-stopped
    hostname: alpine
    privileged: true
    stdin_open: true
    tty: true
    #read_only: false
    environment:
      myName: "lechance"
    ports:
      - 80:80
    networks:
      - net
networks:
  net:
    external: true
