version: "3.8"

services:
  alpine-me:
    build: .
    image: alpine:me
    container_name: alpine-me
    restart: always
    hostname: alpine

    privileged: true

    stdin_open: true
    tty: true
    read_only: false
    environment:
      myName: "lechance"
    networks:
      - net
networks:
  net:
    external: true
