version: "3.8"

services:
  base:
    build: .
    image: lechance/alpine:me
    container_name: base
    restart: unless-stopped
    hostname: alpine

    privileged: true

    ports:
      - 80:80
    stdin_open: true
    tty: true
    read_only: false
    environment:
      myName: "lechance"
    networks:
      - net

networks:
  net:
    external: true
